sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
 
      - docker build -t failender/dgo-frontend:$TRAVIS_BRANCH .
      - docker login -u failender -p $DOCKER_PASS
      - docker push failender/dgo-frontend

